# the BioSample accession
biosample_accession: SAMN34380495

# name of CSV file listing barcode runs to uploade
barcode_runs: barcode_runs_to_upload.csv

#
sample_name: Adimab_MAP_barcodes

# the following come from the SRA FTP upload instructions
ftp_username: subftp
ftp_account_folder: uploads/tyler.n.starr_gmail.com_LMpRB4Tu

# Meaningful name for this sample's FTP folder:
ftp_subfolder: Adimab_MAP_barcodes
